### ISSUE TITLE
'Class 'SoundStreamPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult' while compiling.

### ISSUE THREAD

**Issue by JHM69** [CasperPas/flutter-sound-stream#58]
I am using sound_stream for Record stream but I am facing this error when I try to install it on Android.
Note: its working fine in iOS. 

> I/flutter ( 7733): run app PasApp()
e: /home/jhm69/.pub-cache/hosted/pub.dev/sound_stream-0.3.0/android/src/main/kotlin/vn/casperpas/sound_stream/SoundStreamPlugin.kt: (45, 8): Class 'SoundStreamPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /home/jhm69/.pub-cache/hosted/pub.dev/sound_stream-0.3.0/android/src/main/kotlin/vn/casperpas/sound_stream/SoundStreamPlugin.kt: (182, 5): 'onRequestPermissionsResult' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sound_stream:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 24s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by yjsplay2002** [comment]
I get same error. Any clue?

**Comment by JHM69** [comment]
> I'm getting the same error. Any clues?

I have fixed that error and made a pull request. But its not yet marged. Here is the pull request:
https://github.com/CasperPas/flutter-sound-stream/pull/59
The fixed repo is here:
https://github.com/JHM69/flutter-sound-stream

**Comment by yjsplay2002** [comment]
Thanks. I have checked the issue. Sorry for the duplicate question.

**Comment by bisketashwin** [comment]
This issue is still showing, 
please evaluate and merge this fix make it available.

**Comment by CasperPas** [comment]
> > I'm getting the same error. Any clues?
> 
> I have fixed that error and made a pull request. But its not yet marged. Here is the pull request: #59
> 
> The fixed repo is here: https://github.com/JHM69/flutter-sound-stream

Sorry for the late response. 🙏
I've checked the PR and it seems the condition about `grantResults` will always be `true`. Could you please change that too? Then I'll merge ASAP.
Thank you!

![image](https://github.com/CasperPas/flutter-sound-stream/assets/330295/680525eb-d6d0-4f7e-ba30-cdc86310c69d)

**Comment by djireland** [comment]
I'm getting the same error. Was this merged in?

**Comment by JHM69** [comment]
> > > I'm getting the same error. Any clues?
> > 
> > 
> > I have fixed that error and made a pull request. But its not yet marged. Here is the pull request: #59
> > The fixed repo is here: https://github.com/JHM69/flutter-sound-stream
> 
> Sorry for the late response. 🙏 I've checked the PR and it seems the condition about `grantResults` will always be `true`. Could you please change that too? Then I'll merge ASAP. Thank you!
> 
> ![image](https://private-user-images.githubusercontent.com/330295/293825146-680525eb-d6d0-4f7e-ba30-cdc86310c69d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNTgyNDgsIm5iZiI6MTcxMjM1Nzk0OCwicGF0aCI6Ii8zMzAyOTUvMjkzODI1MTQ2LTY4MDUyNWViLWQ2ZDAtNGY3ZS1iYTMwLWNkYzg2MzEwYzY5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQyMjU5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTNkMDIyNjYxNjM4ZWE2YzA1NWNkNjA0ZjNlMDQ2YjA2MGMwZmRjOWRiOWFkMDcyZWY1NTIyNjIwYzZmYjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wKK9VeE9fNfYwPBRwLQxyxak--TAoTr62VTL-32uQGc)

I have updated that

**Comment by CasperPas** [comment]
Fixed with the latest code. Thanks!
